//
// This file was generated by the Jeddict
//

package springData.domain;

import java.io.Serializable;
import java.util.Objects;

public class UserPK implements Serializable {

   private long userID;

   private int role;

   public UserPK() {
   }

   public UserPK(long userID, int role) {
      this.userID = userID;
      this.role = role;
   }

   public long getUserID() {
      return this.userID;
   }

   public void setUserID(long userID) {
      this.userID = userID;
   }

   public int getRole() {
      return this.role;
   }

   public void setRole(int role) {
      this.role = role;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj == null) {
         return false;
      }
      if (!Objects.equals(getClass(), obj.getClass())) {
         return false;
      }
      final UserPK other = (UserPK) obj;
      if (!java.util.Objects.equals(this.getUserID(), other.getUserID())) {
         return false;
      }
      if (!java.util.Objects.equals(this.getRole(), other.getRole())) {
         return false;
      }
      return true;
   }

   @Override
   public int hashCode() {
      int hash = 7;
      hash = 31 * hash + (int) (this.getUserID() ^ (this.getUserID() >>> 32));
      hash = 31 * hash + Objects.hashCode(this.getRole());
      return hash;
   }

   @Override
   public String toString() {
      return "UserPK{" + " userID=" + userID + ", role=" + role + '}';
   }

}
