//
// This file was generated by the Jeddict
//
package springData.domain;

import java.io.Serializable;
import java.util.Objects;

public class UserPK implements Serializable {

    private Long userID;

    private Long role;

    public UserPK() {
    }

    public UserPK(Long userID, Long role) {
        this.userID = userID;
        this.role = role;
    }

    public Long getUserID() {
        return this.userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public Long getRole() {
        return this.role;
    }

    public void setRole(Long role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final UserPK other = (UserPK) obj;
        if (!java.util.Objects.equals(this.getUserID(), other.getUserID())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getRole(), other.getRole())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getUserID());
        hash = 31 * hash + Objects.hashCode(this.getRole());
        return hash;
    }

    @Override
    public String toString() {
        return "UserPK{" + " userID=" + userID + ", role=" + role + '}';
    }

}