
/**
 * This file was generated by the Jeddict
 */
package springData.domain;

import java.util.ArrayList;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * @author mia17
 */
@Entity
@Table(name = "CAR")
public class Car {

   @Column(length = 10)//, unique = true)
   @Id
   private String registrationNumber;

   @Basic
   private String carName;

   @Basic
   private String carMake;

   @Basic
   private String carColor;

   /**
    * Starting location latitude
    */
   @Basic
   private String latitude;

   /**
    * Starting location longitude
    */
   @Basic
   private String longitude;

   /**
    * Is the car active or not?
    */
   @Type(type = "yes_no")
   @Column(name = "isActive", nullable = false)
   private boolean isActive;

   @Basic(optional = false)
   private int fuelLevel;

    @ManyToOne
    private CarAvailability carAvailability;

    @OneToMany(mappedBy = "car", cascade= {CascadeType.PERSIST, CascadeType.REMOVE}, fetch=FetchType.EAGER)
    private Set<Request> requests;

    public Car() {
    }

    public Car(String registrationNumber, String carColor, String carName, boolean isActive) {
       super();
       this.registrationNumber = registrationNumber;
       this.carColor = carColor;
       this.carName = carName;
       this.isActive = isActive;
    }
    
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public String getCarName() {
        return this.carName;
    }

    public void setCarName(String carName) {
        this.carName = carName;
    }

    public String getCarMake() {
        return this.carMake;
    }

    public void setCarMake(String carMake) {
        this.carMake = carMake;
    }

    public String getCarColor() {
        return this.carColor;
    }

    public void setCarColor(String carColor) {
        this.carColor = carColor;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public int getFuelLevel() {
        return this.fuelLevel;
    }

    public void setFuelLevel(int fuelLevel) {
        this.fuelLevel = fuelLevel;
    }

    public CarAvailability getCarAvailability() {
        return this.carAvailability;
    }

    public void setCarAvailability(CarAvailability carAvailability) {
        this.carAvailability = carAvailability;
    }

    public Set<Request> getRequests() {
        return this.requests;
    }

    public void setRequests(Set<Request> requests) {
        this.requests = requests;
    }

    public void addRequest(Request request) {
        getRequests().add(request);
        request.setCar(this);
    }

    public void removeRequest(Request request) {
        getRequests().remove(request);
        request.setCar(null);
    }

}
