//
// This file was generated by the Jeddict
//
package springData.domain;

import java.io.Serializable;
import java.util.Objects;

public class Car_AvailabilityPK implements Serializable {

    private Long availabilityID;

    private Long car;

    public Car_AvailabilityPK() {
    }

    public Car_AvailabilityPK(Long availabilityID, Long car) {
        this.availabilityID = availabilityID;
        this.car = car;
    }

    public Long getAvailabilityID() {
        return this.availabilityID;
    }

    public void setAvailabilityID(Long availabilityID) {
        this.availabilityID = availabilityID;
    }

    public Long getCar() {
        return this.car;
    }

    public void setCar(Long car) {
        this.car = car;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final Car_AvailabilityPK other = (Car_AvailabilityPK) obj;
        if (!java.util.Objects.equals(this.getAvailabilityID(), other.getAvailabilityID())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getCar(), other.getCar())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getAvailabilityID());
        hash = 31 * hash + Objects.hashCode(this.getCar());
        return hash;
    }

    @Override
    public String toString() {
        return "Car_AvailabilityPK{" + " availabilityID=" + availabilityID + ", car=" + car + '}';
    }

}