/**
 * This file was generated by the Jeddict
 */
package springData.domain;

import java.time.LocalTime;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;

/**
 * @author mia17
 */
@Entity
@IdClass(Car_AvailabilityPK.class)
public class Car_Availability {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long availabilityID;

    @Basic
    private LocalTime availability_time;

    @Basic
    private String accessCode;

    @Id
    @ManyToOne
    private Car car;

    public Long getAvailabilityID() {
        return this.availabilityID;
    }

    public void setAvailabilityID(Long availabilityID) {
        this.availabilityID = availabilityID;
    }

    public LocalTime getAvailability_time() {
        return this.availability_time;
    }

    public void setAvailability_time(LocalTime availability_time) {
        this.availability_time = availability_time;
    }

    public String getAccessCode() {
        return this.accessCode;
    }

    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }

    public Car getCar() {
        return this.car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

}