//
// This file was generated by the Jeddict
//
package springData.domain;

import java.io.Serializable;
import java.util.Objects;

public class InvoicePK implements Serializable {

    private Long invoiceID;

    private Long payment;

    public InvoicePK() {
    }

    public InvoicePK(Long invoiceID, Long payment) {
        this.invoiceID = invoiceID;
        this.payment = payment;
    }

    public Long getInvoiceID() {
        return this.invoiceID;
    }

    public void setInvoiceID(Long invoiceID) {
        this.invoiceID = invoiceID;
    }

    public Long getPayment() {
        return this.payment;
    }

    public void setPayment(Long payment) {
        this.payment = payment;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final InvoicePK other = (InvoicePK) obj;
        if (!java.util.Objects.equals(this.getInvoiceID(), other.getInvoiceID())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getPayment(), other.getPayment())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getInvoiceID());
        hash = 31 * hash + Objects.hashCode(this.getPayment());
        return hash;
    }

    @Override
    public String toString() {
        return "InvoicePK{" + " invoiceID=" + invoiceID + ", payment=" + payment + '}';
    }

}