//
// This file was generated by the Jeddict
//
package springData.domain;

import java.io.Serializable;
import java.util.Objects;

public class PaymentTypePK implements Serializable {

    private Long paymentTypeID;

    private Long payment;

    public PaymentTypePK() {
    }

    public PaymentTypePK(Long paymentTypeID, Long payment) {
        this.paymentTypeID = paymentTypeID;
        this.payment = payment;
    }

    public Long getPaymentTypeID() {
        return this.paymentTypeID;
    }

    public void setPaymentTypeID(Long paymentTypeID) {
        this.paymentTypeID = paymentTypeID;
    }

    public Long getPayment() {
        return this.payment;
    }

    public void setPayment(Long payment) {
        this.payment = payment;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final PaymentTypePK other = (PaymentTypePK) obj;
        if (!java.util.Objects.equals(this.getPaymentTypeID(), other.getPaymentTypeID())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getPayment(), other.getPayment())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getPaymentTypeID());
        hash = 31 * hash + Objects.hashCode(this.getPayment());
        return hash;
    }

    @Override
    public String toString() {
        return "PaymentTypePK{" + " paymentTypeID=" + paymentTypeID + ", payment=" + payment + '}';
    }

}