/**
 * This file was generated by the Jeddict
 */
package springData.domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToOne;

/**
 * @author mia17
 */
@Entity
@IdClass(PaymentTypePK.class)
public class PaymentType {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long paymentTypeID;

    @Basic
    private String paymentTypeDescription;

    @Basic
    private String paymentTypeCode;

    @Id
    @OneToOne
    private Payment payment;

    public Long getPaymentTypeID() {
        return this.paymentTypeID;
    }

    public void setPaymentTypeID(Long paymentTypeID) {
        this.paymentTypeID = paymentTypeID;
    }

    public String getPaymentTypeDescription() {
        return this.paymentTypeDescription;
    }

    public void setPaymentTypeDescription(String paymentTypeDescription) {
        this.paymentTypeDescription = paymentTypeDescription;
    }

    public String getPaymentTypeCode() {
        return this.paymentTypeCode;
    }

    public void setPaymentTypeCode(String paymentTypeCode) {
        this.paymentTypeCode = paymentTypeCode;
    }

    public Payment getPayment() {
        return this.payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

}